#!/bin/sh

# Spécifiez l'emplacement de votre exécutable `mysql` et de `mysqldump`
# Si vous avez installé XAMPP à l'emplacement par défaut, cela pourrait ressembler à ceci:
MYSQL="C:/xampp/mysql/bin/mysql.exe"
MYSQLDUMP="C:/xampp/mysql/bin/mysqldump.exe"

# Remplacez par les détails de votre base de données
DB_NAME="cs_2023_cafe"
DB_USER="root"
DUMP_FILE="C:/Users/jba/PhpstormProjects/2023-CSCafe/sql/$DB_NAME.sql"

# (Optionnel) Sauvegardez la base de données actuelle avant de restaurer
"$MYSQLDUMP" -u $DB_USER $DB_NAME > "C:/Users/jba/PhpstormProjects/2023-CSCafe/sql/backup_$(date +%Y%m%d%H%M%S).sql"

# Restaurez la base de données à partir du dump
"$MYSQL" -u $DB_USER $DB_NAME < $DUMP_FILE

exit 0