#!/bin/sh
# Spécifiez l'emplacement de votre exécutable `mysqldump`
# Si vous avez installé XAMPP à l'emplacement par défaut, cela pourrait ressembler à ceci:
MYSQLDUMP="C:/xampp/mysql/bin/mysqldump.exe"
 
# Remplacez par les détails de votre base de données
DB_NAME="cs_2023_cafe"
DB_USER="root"
DUMP_FILE="C:/Users/jba/PhpstormProjects/2023-CSCafe/sql/$DB_NAME.sql"

"$MYSQLDUMP" -u $DB_USER $DB_NAME > $DUMP_FILE

# Ajoutez le dump à la liste des fichiers à commettre
git add $DUMP_FILE
 
exit 0